#ifndef JVMAN_INSTALLER_RESOURCE_H
#define JVMAN_INSTALLER_RESOURCE_H

#define IDD_JVMAN_LANGUAGE 101
#define IDD_JVMAN_UNINSTALL_SCOPE 102
#define IDD_JVMAN_PROGRESS 103

#define IDC_JVMAN_LANGUAGE_LABEL 1001
#define IDC_JVMAN_LANGUAGE_COMBO 1002

#define IDC_JVMAN_UNINSTALL_SCOPE_PROMPT 1101
#define IDC_JVMAN_UNINSTALL_PROGRAM_ONLY 1102
#define IDC_JVMAN_UNINSTALL_DATA 1103
#define IDC_JVMAN_UNINSTALL_ALL 1104

#define IDC_JVMAN_PROGRESS_TEXT 1201
#define IDC_JVMAN_PROGRESS_BAR 1202

#endif
